DefaultContentLanguage = "en"
author = "He Yeshuang"
baseURL = "http://127.0.0.1:8080/"
copyright = "Copyright © 2008–2019"
disqusShortname = "YOURSHORTNAME"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"
theme = "hugo-theme-tokiwa"
title = "WARPR Blog Web Site"
uglyURLs = true

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/exampleFont" 
description = """
Tokiwa-iro is the theme color of this site.
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTeX$
useChineseFonts = true 
postDateFormat = "2006-1-2"
#social = true

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post.html"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags.html"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories.html"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about.html"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
url = "/tags"
[params.social]
bilibili = "http://example.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "http://example.com/"
mail = "mailto:anon@example.com"
twitter = "https://twitter.com/"
weibo = "http://example.com/"
youtube = "https://youtube.com/"
zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]
